// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/salary.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SalaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Base          float64                `protobuf:"fixed64,2,opt,name=base,proto3" json:"base,omitempty"`
	BonusPercent  float64                `protobuf:"fixed64,3,opt,name=bonus_percent,json=bonusPercent,proto3" json:"bonus_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalaryRequest) Reset() {
	*x = SalaryRequest{}
	mi := &file_proto_salary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalaryRequest) ProtoMessage() {}

func (x *SalaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalaryRequest.ProtoReflect.Descriptor instead.
func (*SalaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_salary_proto_rawDescGZIP(), []int{0}
}

func (x *SalaryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SalaryRequest) GetBase() float64 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *SalaryRequest) GetBonusPercent() float64 {
	if x != nil {
		return x.BonusPercent
	}
	return 0
}

type SalaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TotalSalary   float64                `protobuf:"fixed64,2,opt,name=total_salary,json=totalSalary,proto3" json:"total_salary,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalaryResponse) Reset() {
	*x = SalaryResponse{}
	mi := &file_proto_salary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalaryResponse) ProtoMessage() {}

func (x *SalaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalaryResponse.ProtoReflect.Descriptor instead.
func (*SalaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_salary_proto_rawDescGZIP(), []int{1}
}

func (x *SalaryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SalaryResponse) GetTotalSalary() float64 {
	if x != nil {
		return x.TotalSalary
	}
	return 0
}

func (x *SalaryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_salary_proto protoreflect.FileDescriptor

const file_proto_salary_proto_rawDesc = "" +
	"\n" +
	"\x12proto/salary.proto\x12\x06salary\"\\\n" +
	"\rSalaryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04base\x18\x02 \x01(\x01R\x04base\x12#\n" +
	"\rbonus_percent\x18\x03 \x01(\x01R\fbonusPercent\"a\n" +
	"\x0eSalaryResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\ftotal_salary\x18\x02 \x01(\x01R\vtotalSalary\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2O\n" +
	"\rSalaryService\x12>\n" +
	"\rComputeSalary\x12\x15.salary.SalaryRequest\x1a\x16.salary.SalaryResponseB\x0fZ\r./proto;protob\x06proto3"

var (
	file_proto_salary_proto_rawDescOnce sync.Once
	file_proto_salary_proto_rawDescData []byte
)

func file_proto_salary_proto_rawDescGZIP() []byte {
	file_proto_salary_proto_rawDescOnce.Do(func() {
		file_proto_salary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_salary_proto_rawDesc), len(file_proto_salary_proto_rawDesc)))
	})
	return file_proto_salary_proto_rawDescData
}

var file_proto_salary_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_salary_proto_goTypes = []any{
	(*SalaryRequest)(nil),  // 0: salary.SalaryRequest
	(*SalaryResponse)(nil), // 1: salary.SalaryResponse
}
var file_proto_salary_proto_depIdxs = []int32{
	0, // 0: salary.SalaryService.ComputeSalary:input_type -> salary.SalaryRequest
	1, // 1: salary.SalaryService.ComputeSalary:output_type -> salary.SalaryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_salary_proto_init() }
func file_proto_salary_proto_init() {
	if File_proto_salary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_salary_proto_rawDesc), len(file_proto_salary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_salary_proto_goTypes,
		DependencyIndexes: file_proto_salary_proto_depIdxs,
		MessageInfos:      file_proto_salary_proto_msgTypes,
	}.Build()
	File_proto_salary_proto = out.File
	file_proto_salary_proto_goTypes = nil
	file_proto_salary_proto_depIdxs = nil
}
