// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/salary.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SalaryService_ComputeSalary_FullMethodName = "/salary.SalaryService/ComputeSalary"
)

// SalaryServiceClient is the client API for SalaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SalaryServiceClient interface {
	ComputeSalary(ctx context.Context, in *SalaryRequest, opts ...grpc.CallOption) (*SalaryResponse, error)
}

type salaryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSalaryServiceClient(cc grpc.ClientConnInterface) SalaryServiceClient {
	return &salaryServiceClient{cc}
}

func (c *salaryServiceClient) ComputeSalary(ctx context.Context, in *SalaryRequest, opts ...grpc.CallOption) (*SalaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SalaryResponse)
	err := c.cc.Invoke(ctx, SalaryService_ComputeSalary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SalaryServiceServer is the server API for SalaryService service.
// All implementations must embed UnimplementedSalaryServiceServer
// for forward compatibility.
type SalaryServiceServer interface {
	ComputeSalary(context.Context, *SalaryRequest) (*SalaryResponse, error)
	mustEmbedUnimplementedSalaryServiceServer()
}

// UnimplementedSalaryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSalaryServiceServer struct{}

func (UnimplementedSalaryServiceServer) ComputeSalary(context.Context, *SalaryRequest) (*SalaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComputeSalary not implemented")
}
func (UnimplementedSalaryServiceServer) mustEmbedUnimplementedSalaryServiceServer() {}
func (UnimplementedSalaryServiceServer) testEmbeddedByValue()                       {}

// UnsafeSalaryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SalaryServiceServer will
// result in compilation errors.
type UnsafeSalaryServiceServer interface {
	mustEmbedUnimplementedSalaryServiceServer()
}

func RegisterSalaryServiceServer(s grpc.ServiceRegistrar, srv SalaryServiceServer) {
	// If the following call pancis, it indicates UnimplementedSalaryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SalaryService_ServiceDesc, srv)
}

func _SalaryService_ComputeSalary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SalaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SalaryServiceServer).ComputeSalary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SalaryService_ComputeSalary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SalaryServiceServer).ComputeSalary(ctx, req.(*SalaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SalaryService_ServiceDesc is the grpc.ServiceDesc for SalaryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SalaryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "salary.SalaryService",
	HandlerType: (*SalaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputeSalary",
			Handler:    _SalaryService_ComputeSalary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/salary.proto",
}
